packages/header/package.json
packages/header/src/header.tsx
packages/header/src/items/burger.tsx
packages/header/src/items/link.tsx
packages/header/src/items/mobileMenu.tsx
packages/header/stories/Header.stories.tsx

- added GTM tracking
- specific events for phone and burger clicks

Header tracking

---

packages/footer/package.json
packages/footer/src/defaultFooter.tsx
packages/footer/utils/locales.ts

- typo in translation fixed
- link fixed

footer hotfix

---

.changeset/red-moose-whisper.md
packages/brandingLogo/src/brandingLogo.tsx
packages/footer/src/envkv.tsx
packages/footer/src/footerContainer.tsx
packages/footer/src/trustfulSection/trustfulContainer.tsx
packages/header/src/header.tsx
packages/header/src/index.ts
packages/header/src/items/link.tsx
packages/header/src/items/mobileMenu.tsx
packages/header/stories/Header.stories.tsx
packages/header/tests/Header.test.tsx

https://instamotion.atlassian.net/browse/RT-247
* also minor footer margin fixes

RT-247: HEADER: Fix issues

---

.changeset/tender-books-attend.md
packages/header/src/header.tsx

Fix header

---

.changeset/young-parrots-visit.md
packages/checkbox/src/checkbox.tsx
packages/checkbox/stories/checkbox.stories.tsx
packages/input/stories/input.stories.tsx

HT-221: checkbox label fix

---

.changeset/short-cows-give.md
packages/footer/src/assets/seal-quality.tsx
packages/footer/src/assets/seal-return.tsx
packages/footer/src/assets/seal-warranty.tsx
packages/ribbon/stories/ribbon.stories.tsx
packages/toggle/stories/toggle.stories.tsx

clip-rule -> clipRule
fill-rule -> fillRule
ribbon  story fix

minor fixes

---

.changeset/great-penguins-applaud.md
packages/howItWorks/src/howItWorks.tsx
packages/howItWorks/stories/howItWorks.stories.tsx
packages/howItWorks/tests/howItWorks.test.tsx

https://instamotion.atlassian.net/browse/HT-278

Ht 278 progress bar

---

.changeset/strong-windows-wait.md
package.json
packages/footer/package.json
packages/footer/src/mailSection/mailContent.tsx
yarn.lock

https://instamotion.atlassian.net/browse/RT-555

CrossEngage - Add event for Footer

---

package-lock.json
packages/footer/src/defaultFooter.tsx
packages/header/src/header.tsx

Updated phone number to a new one.

Update phone number in headers and footers

---

.changeset/small-flies-cry.md
packages/footer/src/menu/menuItemHeader.tsx

https://instamotion.atlassian.net/browse/RT-585

[rt-585] Wrong font for footer texts

---

.changeset/thin-kids-raise.md
packages/footer/src/footer.tsx

https://instamotion.atlassian.net/browse/RT-627

RT-627: added gtm init event for A/B tests

---

.changeset/odd-avocados-sniff.md
packages/footer/src/footer.tsx
packages/footer/utils/detectSSR.test.tsx
packages/footer/utils/detectSSR.tsx

https://instamotion.atlassian.net/browse/RT-627

RT-627: fixed footer tests, refactor

---

.changeset/fresh-chairs-teach.md
packages/footer/src/defaultFooter.tsx
packages/footer/utils/locales.ts
packages/header/src/header.tsx
packages/header/src/items/link.tsx
packages/header/src/items/mobileMenu.tsx
packages/header/utils/locales.ts

https://instamotion.atlassian.net/browse/RT-625

RT-625: changed links, header, footer

---

.changeset/famous-panthers-switch.md
packages/footer/src/defaultFooter.tsx

https://instamotion.atlassian.net/browse/RT-625

RT-625: changed links a bit more

---

.changeset/chilled-lies-shop.md
packages/footer/src/defaultFooter.tsx
packages/footer/src/szFooter.tsx

Update footer with new urls

---

.changeset/spotty-adults-crash.md
packages/input/src/input.tsx

https://instamotion.atlassian.net/browse/UT-413

[fix/ut-413] Validation is not adjusted

---

.changeset/afraid-toys-joke.md
packages/imHeader/src/default/index.tsx

Fix header width

---

.changeset/great-humans-rush.md
packages/footer/src/newFooter/defaultFooter.tsx

Related PR: https://github.com/Instamotion/im-parkplatz/pull/306

[UT-816] Update anchor link

---

packages/highlights/build/tsconfig.cjs.json
packages/highlights/build/tsconfig.esm.json
packages/highlights/package.json
packages/highlights/src/highlights.tsx
packages/highlights/src/index.ts
packages/highlights/stories/highlights.stories.tsx
packages/highlights/tests/highlights.test.tsx
packages/highlights/tsconfig.json

- Add highlights from PDP to the component library
- Create highlights design for checkout

[UT-841 & UT-875] Add highlights

---

.changeset/new-tomatoes-poke.md
package-lock.json
packages/faq/build/tsconfig.cjs.json
packages/faq/build/tsconfig.esm.json
packages/faq/package.json
packages/faq/src/accordion.tsx
packages/faq/src/faq.tsx
packages/faq/src/index.ts
packages/faq/stories/faq.stories.tsx
packages/faq/tests/faq.test.tsx
packages/faq/tsconfig.json

[UT-840] Integrate FAQ

---

.changeset/spicy-pears-grow.md
packages/FinancingTab/readme.md
packages/FinancingTab/src/FinancingTab.tsx
packages/FinancingTab/src/styles.tsx
packages/FinancingTab/stories/FinancingTab.stories.tsx
packages/FinancingTab/utils/locales.ts

This PR implements collapsed view:

[UT-843] Add collapsed view

---

.changeset/fresh-dryers-vanish.md
packages/FinancingTab/readme.md
packages/FinancingTab/src/FinancingTab.tsx
packages/FinancingTab/utils/locales.ts

This PR implements financing reset button, as per checkout design update.

[UT-843] Add financing reset button

---

.changeset/blue-crews-exercise.md
packages/input/package.json

adopted the new version of the label

UT-948 label version adoptation

---

.changeset/curly-cherries-move.md
.changeset/funny-meals-laugh.md
.changeset/mighty-dogs-roll.md
packages/checkbox/src/checkbox.tsx

passed the required prop from checkbox to its label

UT-948 checkout label

---

.changeset/fair-pianos-admire.md
packages/input/src/styles.tsx
packages/styledDropdown/src/styles.tsx

changed fontSize of errors label

UT-948 Errors label

---

.changeset/purple-rats-teach.md
packages/checkbox/src/newStyles.tsx

changed the font size of checkbox error label

UT-948 changed the font size of checkbox error label
